-- Stage: Add AI suggested action column for proactive team guidance.
-- ai_suggested_action is a short imperative sentence generated by the classifier.

ALTER TABLE feedback_items
  ADD COLUMN IF NOT EXISTS ai_suggested_action text;
